### ISSUE TITLE
Constrain Width → Maximum Width units should be characetrs

### ISSUE THREAD

**Issue by stranak** [simonbs/Runestone#201] opened 2022-09-25 15:12 UTC
**Describe the bug**
The Page Guide is set in characters (em widths, columns), but maximum text width is not. As a result, they cannot be set to the same values and they mismatch visually.

**To Reproduce**
Set Page Guide to 80 (common default of e.g. vim to wrap lines) and then try to set Maximum Width to match this.

**Expected behavior**
Using columns for Maximum Width. 

Possibly being able to link these, e.g. by Constrain Width → Follow Page Guide. But that would be a feature request :-)

**Comment by simonbs** [comment] 2022-09-26 09:14
Hi @stranak,

Thanks for opening this issue. It seems related to the Runestone text editor app rather than the open-source framework that the app was built on. This repository contains the open-source framework. You're welcome to send feedback to `mail at runestone dot app`.

It's a sound idea to have the Maximum Width being expressed in number of characters rather than number of pixels, however, it is not a bug that this is not the case at the moment. I'll consider if this should be changed for a future release.

I'll close this issue for now since it doesn't seem to be concerned with the framework.

**Closed by simonbs** 2022-09-26 09:14 UTC
Labels: bug
