### ISSUE TITLE
Behaviour of command+left/right with line breaks

### ISSUE THREAD

**Issue by nighthawk** [simonbs/Runestone#148] opened 2022-08-24 08:09 UTC
**Describe the bug**

I have a question about the behaviour of Runestone when having line breaks and using command + left/right to go to the beginning and end of the line. How it behaves doesn't match my expectation and makes me stop and think what happened.

Runestone jumps to the end of the "logical" or "unbroken" line, which might be further down, but I expect it to jump to the end of the "broken" line.

**To Reproduce**

Use Runestone and have a long line of text, enable line breaks. Press command + left/right.

I've tested this on both Catalyst and iPad and it works the same in both.

**Expected behavior**

The caret jumps to the end of the broken line (like Xcode)

https://user-images.githubusercontent.com/22646/186363628-379e1dd5-7909-483e-b8f5-a43e2ef5da75.mov

**Actual behavior**

The caret jumps to the end of the unbroken line, which might be on the next line down (or further).

Similarly with command + left. It'd be nice if it jumped to the first non-whitespace character then, too.

https://user-images.githubusercontent.com/22646/186363590-d15e9d64-2e51-43d3-9432-c2fb3db1439c.mov

---

Is this expected behaviour? Is there some way to customise this already? While trying to see why this happened, I noticed that it appears to be UIKit setting the selected text range -- see below. If you agree that this behaviour should be changed, @simonbs , but you don't have time to tackle this, you can also point me in the direction to fix it myself and I'll give it a shot. I tried but couldn't figure out where's the logical place to hook into.

```
// MARK: - UITextInput
    var selectedTextRange: UITextRange? {
        get {
            if let range = _selectedRange {
                return IndexedRange(range)
            } else {
                return nil
            }
        }
        set {
            // We should not use this setter. It's intended for UIKit to use.
            // It'll invoke the setter in various scenarios, for example when navigating the text using the keyboard.
            let newRange = (newValue as? IndexedRange)?.range
            if newRange != _selectedRange {
                shouldNotifyInputDelegateAboutSelectionChangeInLayoutSubviews = true
                _selectedRange = newRange
                delegate?.textInputViewDidChangeSelection(self)
            }
        }
    }
```

**Comment by simonbs** [comment] 2022-08-26 07:42
@nighthawk Thanks for filing this feedback. It's currently working as expected, since I made this behavior to match the Nova text editor. However, I think this was before I made the decision to have as much behavior as possible match UITextView and I've just tested with an instance of UITextView which will navigate to the end/beginning of a line fragment.

Therefore, I think the default behavior should be changed in Runestone. I'll have a look at how we can best approach this.

**Comment by nighthawk** [comment] 2022-08-26 09:24
Thanks for the reply. That makes sense.

That would mean the current behaviour might then be what some users are used to -- if they come from Nova or have used Runestone for a while. Could this be made a setting? That way users could pick the behaviour that they are used to.

**Comment by simonbs** [comment] 2022-08-27 15:19
@nighthawk Phew, this took much longer to implement than I had imagined. It turned out to be quite complicated to get the behavior to match UITextView but I think I've finally got something that's quite close in PR #153. 

Would you be up for trying these changes out in your project to see if the updated behavior is closer to what you expect?

> Could this be made a setting?

When I started implementing this yesterday, I thought I'd make it a setting. However, I quickly decided not to do that, at least not for now. The reason is that the changes to properly support CTRL+A and CTRL+E the way UITextView does have turned out to be quite elaborate, and I'd prefer not to have maintain two different behaviors if I can avoid it.

While users coming from other text editors, such as Nova, may not expect that jumping to the beginning or end will in fact jump within the select line fragment, I think it's safe to make that the default (and only) behavior for now, since it matches the behavior of UITextView.

**Comment by simonbs** [comment] 2022-08-27 18:59
[This Twitter thread](https://twitter.com/steveshepard/status/1563597362538287104) have gotten my in doubt what the correct behavior is for Runestone:
Aligning with UITextView or popular code editors? Will need to put some more thought into this.

**Comment by nighthawk** [comment] 2022-08-28 03:27
Thanks for looking into this so quickly and digging into this!

I did more testing on this in Xcode and VS Code and UITextView (in a Mac Catalyst app), and in my testing the behaviour is consistent across them, and this issue could be renamed "Command+Left/Right should not work like Ctrl+A/E)". They show this behaviour:

1.) Cmd+Left/Right goes to the beginning/end of the line fragment, ignoring trailing whitespace (i.e., it goes the the first/last non-whitespace character in the line fragment).
2.) Ctrl+A/E goes to the beginning/end of the line, including trailing whitespace.

In my testing of Runestone it treats them the same — both in the main branch and your PR, with the main branch following 2) and the PR following 1). So I think the PR should be changed to maintain the old behaviour (2) for Ctrl+A/E, and adopt the new behaviour (1) for Cmd+Left/Right.

**Comment by simonbs** [comment] 2022-08-28 09:26
> I did more testing on this in Xcode and VS Code and UITextView (in a Mac Catalyst app), and in my testing the behaviour is consistent across them, and this issue could be renamed "Command+Left/Right should not work like Ctrl+A/E)".

Interesting! Following your message I've also done some more testing and found the same as you but it also turns out that the behavior of UITextView differs between iOS and Mac Catalyst. The following table shows my results and the apps I used for testing. Granted, I didn't test with a lot of apps but I think it makes sense to compare Runestone against these apps.

|Platform|Apps Used for Testing|Ctrl+A|Ctrl+E|Cmd+Left|Cmd+Right|
|-|-|-|-|-|-|
|Mac|Xcode, Nova, and Notes|Beginning of line|End of line|Beginning of line fragment|End of line fragment|
|iOS|Swift Playground, Textastic, and Notes|Beginning of line fragment|End of line fragment|Beginning of line fragment|End of line fragment|
|Mac Catalyst|A sample project of mine that's just a view controller with a plain UITextView|Beginning of line|End of line|Beginning of line fragment|End of line fragment|

Mac and Mac Catalyst apps are aligned but iOS apps will always move the the beginning/end of a line fragment. I think the above table supports [the theory presented by Steve Shephard](https://twitter.com/steveshepard/status/1563597362538287104) that the behavior of Ctrl+A and Ctrl+E is incorrect in iOS apps. That said, Runestone should probably have the same "incorrect" behavior to align with other iOS apps.

> In my testing of Runestone it treats them the same — both in the main branch and your PR, with the main branch following 2) and the PR following 1). So I think the PR should be changed to maintain the old behaviour (2) for Ctrl+A/E, and adopt the new behaviour (1) for Cmd+Left/Right.

I agree that this is something that should be corrected in Runestone.

None of this should be _that_ difficult to adjust. It just bothers me that I don't know if iOS and Mac Catalyst should give me the correct behavior for free if I somehow tweak my implementation of UITextInput. I feel like it should, since it automatically handles these keyboard shortcuts but not with the behavior outlined in the table above. Alternatively, I should override handle this keyboard shortcuts myself and implement the correct behavior. I'd like to avoid that if UITextInput is supposed to be giving it to me for free but as far as I can tell, Apple's documentation doesn't mention this anywhere.

**Comment by simonbs** [comment] 2022-08-28 15:50
I've looked into this again and found that UITextInput will _mostly_ provide the expected behavior of Ctrl+A, Ctrl+E, Cmd+Left, and Cmd+Right across all platforms when the implementation of UITextInputStringTokenizer matches what UIKit expects.

Getting that to correct is difficult though and the documentation is extremely lacking. Through trial and error I've come up with the implementation in https://github.com/simonbs/Runestone/pull/153/commits/b77f951f33b0ff351edf0bd05884913dca0d9e4a.

So far I've identified two shortcuts.

**Missing (meaningful) implementations in UITextInputStringTokenizer**

`isPosition(_:atLineBoundaryInDirection:)` and `-isPosition(_:atParagraphBoundaryInDirection:)` have no meaningful implementation. As written in the documents inside the two functions, I have been unable to get the correct behavior when returning true in those functions. Apple's documentation has not been helpful at all.

However, I haven't found any consequences to returning false in all cases so far.

**Jumping to the beginning/end of a line is partly faked**

From my testing, it seems common to place the caret at the following line fragment when it would otherwise be behind the last character in a line fragment. It seems that UITextView does that as well as all macOS apps.

This makes jumping to the beginning and end of a line fragment tricky since jumping to the end of a line fragment will cause the caret to be placed at the following line fragment. That's not what the user expects. UITextView somehow works around this but it's not clear how.

Textastic seems to work around this by moving to the second last character in a line when jumping to the end of a line. In some cases this gives the exact result that the user expects but in other cases it's a bit strange. I've adopted the same behavior in Runestone for now. If Textastic have been able to get away with this shortcoming, I imagine that Runestone will be able to as well.

**Comment by simonbs** [comment] 2022-08-28 15:52
I've looked into this again and found that UITextInput will _mostly_ provide the expected behavior of Ctrl+A, Ctrl+E, Cmd+Left, and Cmd+Right across all platforms when the implementation of UITextInputStringTokenizer matches what UIKit expects.

Getting that to correct is difficult though and the documentation is extremely lacking. Through trial and error I've come up with the implementation in https://github.com/simonbs/Runestone/pull/153/commits/b77f951f33b0ff351edf0bd05884913dca0d9e4a.

So far I've identified two shortcomings.

**Missing (meaningful) implementations in UITextInputStringTokenizer**

`isPosition(_:atLineBoundaryInDirection:)` and `-isPosition(_:atParagraphBoundaryInDirection:)` have no meaningful implementation. As written in the documents inside the two functions, I have been unable to get the correct behavior when returning true in those functions. Apple's documentation has not been helpful at all.

However, I haven't found any consequences to returning false in all cases so far.

**Jumping to the beginning/end of a line is partly faked**

From my testing, it seems common to place the caret at the following line fragment when it would otherwise be behind the last character in a line fragment. It seems that UITextView does that as well as all macOS apps.

This makes jumping to the beginning and end of a line fragment tricky since jumping to the end of a line fragment will cause the caret to be placed at the following line fragment. That's not what the user expects. UITextView somehow works around this but it's not clear how.

Textastic seems to work around this by moving to the second last character in a line when jumping to the end of a line. In some cases this gives the exact result that the user expects but in other cases it's a bit strange. I've adopted the same behavior in Runestone for now. If Textastic have been able to get away with this shortcoming, I imagine that Runestone will be able to as well.

**Next steps**

I hope to implement unit tests for some of this new logic so it'll be easier to maintain in the future. In the mean time I'd greatly appreciate if you, @nighthawk, will help me test this in your project to see if the updated implementation (almost) provides the behavior you're expecting.

**Comment by nighthawk** [comment] 2022-08-30 06:58
This works very well and feels great now. 

That shortcut from Textastic seems fine — it's a subtle difference that has no meaningful impact to navigating around line fragments in my testing. At least it didn't do anything that felt off or unexpected.

I'll keep a look out for further related issues, but in my use so far this is a big improvement, so I'm very happy with it. Thanks a lot, @simonbs!

**Comment by simonbs** [comment] 2022-08-30 07:17
Glad to hear that! I'll make #153 with the changes are merged soon. I plan to add a few unit tests to some of the new logic. I hope to have that time for that this evening.

Thanks a lot for reporting the issue, helping me test the solution, and providing feedback along the way, @nighthawk!

**Closed** 2022-09-03 09:49 UTC
Labels: enhancement
