### ISSUE TITLE
Crash after subsequent `setState` calls

### ISSUE THREAD

**Issue by haldun** [simonbs/Runestone#226] opened 2022-10-28 12:52 UTC
**Describe the bug**

When we initialize the TextView with only a text and then call `setState` again with a language and a theme, the TextView crashes at https://github.com/simonbs/Runestone/blob/bb2451158a4f0d67d2ac310127cc624513afdeaf/Sources/Runestone/RedBlackTree/RedBlackTree.swift#L37 when I interact with the view like double tapping on an empty line, etc.

**To Reproduce**

I have created a branch with a minimal example here https://github.com/simonbs/Runestone/compare/main...haldun:Runestone:haldun/crash?expand=1 

I can repro this on the `main` branch of Runestone as of the commit https://github.com/simonbs/Runestone/commit/bb2451158a4f0d67d2ac310127cc624513afdeaf

**Expected behavior**

Should not crash.

**Screenshots**

N/A.

**Additional context**

N/A.

**Comment by simonbs** [comment] 2022-10-28 16:14
Thanks for reporting this issue. I'll make sure to have a look at it.

**Comment by simonbs** [comment] 2022-10-31 08:24
I suppose this issue is related to #220 and I'm still unable to reproduce it, even on the branch you have linked to. I'm guessing there's something in the timing that I'm getting wrong. I've tried:

1. Delaying the second call to `setState` with a couple of seconds and interacting with the text while only the initial call has been made.
2. Waiting until after the second call to `setState` has been made and then interacting with the text.
3. Tapping the text like crazy as soon as the app launches.

Do you have a flow to reproduce this consistently and if so, can you put a bit more words on it?

Here's a screen recording of me trying various things.

https://user-images.githubusercontent.com/830995/198963711-aab555ee-132a-4fa3-8e08-fb540b5d7b9d.mov

**Comment by simonbs** [comment] 2022-10-31 08:33
> Maybe it does not happen on the device?

I've also tried in the simulator. I started testing on the device because I couldn't reproduce it in the simulator and thought it might only happen on the device.

I'd appreciate if you can gather more data. It's probably just because we're testing this differently and I just need a bit more detail to understand how I should test this.

**Comment by simonbs** [comment] 2022-10-31 14:59
@haldun Thanks for posting the video! That was very helpful and I helped me reproduce the issue.

I believe the issue is fixed by #234 and #235. I'd appreciate if you'll take a moment to verify that the issue also seems to be reolsved on your end with the new changes.

**Comment by simonbs** [comment] 2022-10-31 16:26
Thanks for verifying the fix!

**Closed by simonbs** 2022-10-31 16:26 UTC
Labels: bug
